apiVersion: v1
kind: Service
metadata:
  name: {{ include "dubhub-clone-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "dubhub-clone-chart.dbPort" . }}
      targetPort: {{ include "dubhub-clone-chart.dbPort" . }}
  selector:
    app: {{ include "dubhub-clone-chart.name" . }}