apiVersion: v1
kind: Service
metadata:
  name: {{ include "dubhub-clone-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "dubhub-clone-chart.name" . }}