apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dubhub-clone-chart.fullname" . }}
spec:
  serviceName: {{ include "dubhub-clone-chart.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dubhub-clone-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dubhub-clone-chart.name" . }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5432
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        volumeMounts:
        - name: "{{ .Values.persistentVolume.name }}"
          mountPath: /var/lds/clones
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Values.persistentVolume.name }}"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ .Values.persistentVolume.size }}"
