apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dubhub-clone-chart.fullname" . }}
spec:
  serviceName: {{ include "dubhub-clone-chart.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dubhub-clone-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dubhub-clone-chart.name" . }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ include "dubhub-clone-chart.dbPort" . }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
        volumeMounts:
        - name: "{{ .Values.persistentVolume.name }}"
          mountPath: /var/lds/clones
        - name: dshm
          mountPath: /dev/shm
        - name: sql-scripts
          mountPath: /docker-entrypoint-initdb.d
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "timeout 300 sh -c '{{ include "dubhub-clone-chart.readinessCommand" . }}; {{ include "dubhub-clone-chart.initCommand" . }}'"]
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
        - name: sql-scripts
          configMap:
            name: {{ include "dubhub-clone-chart.fullname" . }}-sql-scripts
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Values.persistentVolume.name }}"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ .Values.persistentVolume.size }}"
