apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-dubhub  # this value must be used in the values.yaml file under storage.StorageClass
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - eu-west-1b # change to the availability zone of your node group